-- Database initialization with sample typing practice texts

CREATE TABLE IF NOT EXISTS text_snippets (
    id BIGSERIAL PRIMARY KEY,
    content TEXT NOT NULL
);

INSERT INTO text_snippets (content) VALUES
('Programming is not just about writing code, but also solving problems, designing system architectures, and continuously learning new technologies. Good programmers know that the key to success is not only knowledge of programming languages, but also the ability to analyze business requirements and translate them into effective technical solutions.'),
('Nowadays, artificial intelligence is revolutionizing almost every field of human activity, from medicine to finance, from transportation to education. Machine learning algorithms can analyze huge datasets in real time, extract valuable insights from them, and make decisions faster than humans ever could before in history.'),
('Blockchain technology, known primarily from cryptocurrencies such as Bitcoin or Ethereum, is finding more and more applications in various sectors of the economy. Its distributed nature and the impossibility of modifying previously recorded data make it ideal for tracking supply chains, verifying the authenticity of documents, and securing financial transactions.'),
('The development of the Internet of Things means that more and more devices in our homes and workplaces are connected to each other and communicate via the network. Smart thermostats automatically adjust the temperature in rooms, refrigerators inform us about missing products, and security systems monitor our homes even when we are thousands of miles away.'),
('Cybersecurity has become one of the most important challenges of the modern digital world. Every day, hackers try to break into the systems of companies, government institutions, and private users, which is why it is so important to use strong passwords, two-factor authentication, and regular software updates to protect your data from unauthorized access.'),
('Quantum computing uses the principles of quantum mechanics to perform calculations in a fundamentally different way from classical computers. Thanks to the phenomenon of superposition and quantum entanglement, these machines can solve certain types of problems exponentially faster, which has the potential to revolutionize cryptography, molecular simulations, and optimization.'),
('Cloud computing enables companies and individual users to access computing resources, storage, and applications over the internet without having to invest in expensive local infrastructure. Models such as Infrastructure as a Service, Platform as a Service, and Software as a Service provide flexibility to scale resources depending on current needs.'),
('Agile methodologies such as Scrum or Kanban have changed the way software is created, emphasizing iterative development, frequent communication with the client, and rapid delivery of business value. Daily stand-ups, sprint planning, retrospectives, and review meetings help programming teams better organize their work and quickly respond to changing requirements.'),
('Microservices architecture involves breaking down a large monolithic application into small, independently deployed services that communicate with each other through well-defined APIs. This approach makes it easier to scale individual system components, speeds up the deployment of new functionalities, and allows different teams to work in parallel on different parts of the application.'),
('DevOps is a culture and set of practices that combine development and operations to automate the processes of building, testing, and deploying software. Continuous integration, continuous delivery, infrastructure as code, and monitoring are key elements that allow teams to deliver value to end users faster and more securely.'),
('Machine learning can be divided into supervised learning, unsupervised learning, and reinforcement learning. In supervised learning, the model is trained on labeled data, in unsupervised learning the algorithm discovers patterns in the data itself, while in reinforcement learning the agent learns to make optimal decisions through interaction with the environment and receiving rewards or penalties for its actions.'),
('Responsive web design is an approach to designing websites that makes them look good on any device, regardless of screen size. Using media queries, flexible grids, and flexible images, developers can create user interfaces that automatically adapt to smartphones, tablets, laptops, and desktop monitors.'),
('NoSQL databases such as MongoDB, Cassandra, or Redis offer an alternative to traditional relational databases, especially in applications requiring very high scalability, flexible data schemas, or low response times. Each type of NoSQL database - document, key-value, column, or graph - is optimized for specific use cases.'),
('Virtualization and containerization are technologies that allow for more efficient use of server resources by running multiple isolated environments on a single physical machine. Docker and Kubernetes have become de facto standards in the world of containerization, enabling easy packaging, distribution, and orchestration of applications in various environments.'),
('Progressive Web Apps combine the best features of web and native applications, offering fast loading, offline capability, push notifications, and installation on the home screen of the device. Using service workers, web app manifest, and HTTPS, developers can create applications that run smoothly even with a weak internet connection.'),
('GraphQL is a query language for APIs created by Facebook that allows clients to precisely specify what data they need, eliminating the over-fetching and under-fetching problems typical of REST APIs. Thanks to strong typing and the ability to retrieve data from multiple resources in a single query, GraphQL significantly simplifies communication between the frontend and backend.'),
('Serverless computing is a model in which the cloud provider automatically manages the infrastructure, allowing developers to focus solely on application code. Functions are executed in response to events and scale automatically, and the user pays only for the actual execution time of the code, which can significantly reduce the operating costs of small and medium-sized projects.'),
('Test-driven development is a programming practice that involves writing tests before we write the actual production code. First we create a test that defines the expected behavior of the function, run it and observe its failure, then write the minimum amount of code needed to pass the test, and finally refactor the code while maintaining its functionality.'),
('Big data refers to extremely large datasets that are difficult to process using traditional methods. Technologies such as Hadoop, Spark, and distributed database systems allow for processing petabytes of information, extracting valuable insights from them, and using them to make strategic business decisions in real time.'),
('Version control systems, especially Git, are an essential tool for every programmer, enabling tracking changes in code, collaborating with other developers, and easily reverting to previous versions of the project. Branching, merging, pull requests, and code reviews are fundamental practices that help teams effectively manage source code and avoid conflicts.'),
('Edge computing moves data processing closer to where it is generated, instead of sending everything to central data centers. This approach reduces latency, saves network bandwidth, and is particularly important for IoT applications, autonomous vehicles, and augmented reality, where milliseconds can be critical to system functionality.'),
('Accessibility in web development means creating websites and web applications so that they are usable for all people, including those with visual, auditory, or motor disabilities. Semantic HTML, appropriate ARIA labels, color contrast, and keyboard support are just some of the aspects that need to be considered when designing an inclusive user experience.'),
('Artificial neural networks are inspired by the biological structure of the human brain and consist of layers of interconnected artificial neurons. Deep learning uses multi-layer neural networks to recognize patterns in huge datasets, achieving remarkable results in image recognition, natural language processing, and generating realistic multimedia content.'),
('Code review is a process in which other team members check the written code before it is merged into the main branch of the project. This not only helps catch bugs and improve code quality, but also promotes knowledge sharing among programmers, unifying coding style, and building a common understanding of system architecture.'),
('Web security encompasses a range of practices aimed at protecting web applications from various threats such as SQL injection, cross-site scripting, cross-site request forgery, or man-in-the-middle attacks. Input data validation, parameterized queries, Content Security Policy, HTTPS, and regular security audits are crucial to ensuring that user data remains secure.');
